#import "../../../template.typ": *
#set page(width: q_width, height: auto, margin: q_margin)
#set text(size: q_size)
#set list(..list_style)
#set enum(numbering: "a)", ..list_style)

A refrigerator working with a coefficient of performance ($"COP"_R$) of 3.5 consumes 2.0 kWh of electrical energy in a single day. It maintains its cold compartment space at $4^degree C$ while rejecting heat to a kitchen environment at $20^degree C$. How much total entropy ($Delta S_"gen"$) is generated by this appliance setup in one day?

#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
$19.6 " kJ/K"$
#pagebreak()
$110.6 " kJ/K"$
#pagebreak()
$-91.0 " kJ/K"$
#pagebreak()
$0 " kJ/K"$

#expl_page(include "../explanations/td_p_5_16.typ")
#prereq_page(include "../prerequisites/entropy_second_law.typ")