#import "../../../template.typ": *
#set page(width: q_width, height: auto, margin: q_margin)
#set text(size: q_size)
#set list(..list_style)
#set enum(numbering: "a)", ..list_style)

What is the theoretical effective emission temperature ($T_e$) of Earth viewed from space as a blackbody, assuming solar constant $S_0 = 1367 "W/m"^2$ and planetary albedo $alpha_p = 0.30$?
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
288 K ($+15 degree"C"$)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
255 K ($-18 degree"C"$)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
273 K ($0 degree"C"$)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
303 K ($+30 degree"C"$)
#expl_page(include "../explanations/climate_01.typ")
#formulae_page(include "../formulae/climate_core.typ")
#steps_page(include "../solution_steps/climate_01.typ")
