#import "../../../template.typ": *
#set page(width: q_width, height: auto, margin: q_margin)
#set text(size: q_size)
#set list(..list_style)
#set enum(numbering: "a)", ..list_style)

According to Wien's displacement law ($lambda_"peak" = b / T$ where $b approx 2898 mu"m" dot "K"$), at what wavelengths do the solar ($T approx 5780 "K"$) and terrestrial ($T approx 255 "K"$) emission spectra peak?
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Sun: $0.50 mu"m"$ (visible); Earth: $11.4 mu"m"$ (thermal infrared)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Sun: $5.0 mu"m"$ (infrared); Earth: $0.5 mu"m"$ (ultraviolet)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Sun: $1.5 mu"m"$ (near-IR); Earth: $25.0 mu"m"$ (far-IR)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Sun: $0.1 mu"m"$ (UV); Earth: $1.0 mu"m"$ (visible)
#expl_page(include "../explanations/climate_03.typ")
#formulae_page(include "../formulae/climate_core.typ")
#steps_page(include "../solution_steps/climate_03.typ")
