#import "../../../template.typ": *
#set page(width: q_width, height: auto, margin: q_margin)
#set text(size: q_size)
#set list(..list_style)
#set enum(numbering: "a)", ..list_style)

Which active carbon reservoir contains approximately $37000-40000 "PgC"$, making it the largest dynamic carbon pool on Earth?
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Terrestrial vegetation ($approx 500 "PgC"$)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Atmosphere ($approx 850 "PgC"$)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Deep Ocean (primarily Dissolved Inorganic Carbon)
#pagebreak()
#set page(width: a_width, height: auto, margin: a_margin)
#set text(size: a_size)
Soils and permafrost ($approx 3700 "PgC"$)
#expl_page(include "../explanations/climate_23.typ")
#formulae_page(include "../formulae/climate_core.typ")
#steps_page(include "../solution_steps/climate_23.typ")
