/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const can_go_back: () => number;
export const get_alternative_html: (a: number) => [number, number];
export const get_alternatives_count: () => number;
export const get_current_question_explanation_html: () => [number, number];
export const get_current_question_explanation_raw: () => [number, number];
export const get_current_question_html: () => [number, number];
export const get_current_question_id: () => [number, number];
export const get_current_question_label: () => [number, number];
export const get_current_question_prerequisites_html: () => [number, number];
export const get_current_question_raw: () => [number, number];
export const get_current_question_references_json: () => [number, number];
export const get_current_selection: () => [number, number];
export const get_explanation_html_by_index: (a: number) => [number, number];
export const get_incorrect_indices: () => [number, number];
export const get_question_html_by_index: (a: number) => [number, number];
export const get_references_json_by_index: (a: number) => [number, number];
export const get_selections_json: () => [number, number];
export const get_topic_stats_json: () => [number, number];
export const get_total_questions: () => number;
export const init_quiz: (a: number, b: number) => [number, number];
export const is_alternative_correct: (a: number) => number;
export const is_finished: () => number;
export const is_graded: () => number;
export const restore_quiz_state: (a: number, b: number, c: number, d: number) => [number, number];
export const select_answer: (a: number, b: number) => void;
export const grade_quiz: () => void;
export const get_current_question_index: () => number;
export const previous_question: () => void;
export const get_score: () => number;
export const next_question: () => void;
export const set_question_index: (a: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
